services:
  - type: web
    name: creatilink-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 manage:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: creatilink-db
          property: connectionString

databases:
  - name: creatilink-db
    databaseName: creatilink
    user: creatilink_user
    plan: free
